
#DATABASE CONFIG
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = ${DB_USER}
quarkus.datasource.password = ${DB_PASSWORD}
quarkus.datasource.jdbc.url = ${DB_URL}


quarkus.hibernate-orm.schema-management.strategy = drop-and-create


#OIDC FOR KEYCLOAK
quarkus.oidc.auth-server-url=${OIDC_AUTH_URL}
quarkus.oidc.client-id=${OIDC_CLIENT_ID}
quarkus.oidc.credentials.secret=${OIDC_CLIENT_SECRET}
quarkus.oidc.application-type=service
